project:
  type: website
execute:
  freeze: auto
website:
  title: "Eric R. Scott"
  site-url: https://www.ericrscott.com/
  repo-url: https://github.com/Aariq/website-quarto
  favicon: icon.png
  twitter-card: 
    creator: "@LeafyEricScott"
  open-graph: true
  navbar:
    title: false
    logo: "icon-192.png"
    logo-alt: "two leaves and a bud with a bite taken out of a leaf"
    background: "light"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: outreach.qmd
        text: Outreach
      # - href: teaching.qmd
      #   text: Teaching
      - href: project.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: Eric Scott cv.pdf
        text: CV
    right:
      - icon: rss
        href: blog.xml
  # repo-url: https://github.com/Aariq/website-quarto
  # repo-actions: [edit, issue]

format:
  html:
    theme: 
      light: 
        - flatly
        - custom.scss # This works
      dark: 
        - darkly
        - custom.scss # This works
    # css: custom.scss # This works in preview, but not when published
    toc: true

editor: visual

