project:
  type: website
  resources: 
    - "robots.txt"
execute:
  freeze: auto
website:
  announcement: 
    icon: exclamation-square
    dismissable: true
    content: "<span style='font-size: 1.05rem;'>I'm looking for work as a research software engineer or data scientist.  Please [contact me](mailto:scottericr@gmail.com) if you are interested or have any leads.</span>"
    position: below-navbar
    type: warning
  title: "Eric R. Scott"
  site-url: https://www.ericrscott.com/
  repo-url: https://github.com/Aariq/website-quarto
  favicon: icon.png
  twitter-card: 
    creator: "@LeafyEricScott"
  open-graph: true
  navbar:
    title: false
    logo: "icon-192.png"
    logo-alt: "two leaves and a bud with a bite taken out of a leaf"
    background: "primary"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: outreach.qmd
        text: Outreach
      # - href: teaching.qmd
      #   text: Teaching
      - href: project.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Code
      - href: Eric Scott cv.pdf
        text: CV
    tools:
      - icon: github
        menu:
          - text: View Source
            href: https://github.com/Aariq/website-quarto
          - text: Report a Bug
            href: https://github.com/Aariq/website-quarto/issues/new
      - icon: rss
        href: blog.xml
        text: Blog RSS feed #shows on hover

format:
  html:
    theme: 
      light: 
        - flatly
        - custom.scss
      dark: 
        - darkly
        - custom.scss
    toc: true

editor: 
  markdown: 
    wrap: sentence

