project:
  type: website
execute:
  freeze: auto
website:
  title: "website-quarto"
  site-url: https://www.ericrscott.com/
  favicon: icon.png
  twitter-card: true
  navbar:
    title: false
    logo: "icon-192.png"
    logo-alt: "two leaves and a bud with a bite taken out of a leaf"
    background: "light"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: outreach.qmd
        text: Outreach
      - href: Eric Scott cv.pdf
        text: CV
    right:
      - icon: rss
        href: blog.xml
  # repo-url: https://github.com/Aariq/website-quarto
  # repo-actions: [edit, issue]

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: custom.scss
    toc: true

editor: visual

