---
title: "New job: Scientific Programmer & Educator"
subtitle: 'at University of Arizona'
author: Eric R. Scott
date: '2022-05-17'
categories:
  - alt-academic-careers
---

My postdoc with the [Bruna lab](https://tropicos.netlify.app/) coming to an end in June and I'm excited to announce my new position as a Scientific Programmer & Educator with University of Arizona!
I thought I'd use this post to explain a little about what I'll be doing and the path I took to get here in case it's helpful for grad students or postdocs exploring career options.
<!--# add link to the landing page for the dept or something? -->

### What is a Scientific Programmer & Educator?

The "Scientific Programmer" part refers to the research half of the job.
I'll be collaborating with faculty, grad students, and postdocs in the [College of Agriculture and Life Sciences](https://ag.arizona.edu/) on research; offering my skills in statistics, data science, data visualization, data management, reproducibility, etc.

The "Educator" part refers to my role as a data science trainer where I will develop trainings, workshops, and tutorials to improve the data science capacity of researchers at University of Arizona.

For both roles, I have a lot of flexibility so I'm looking forward to continuing to work on multivariate analyses, ecological modeling, demography, and reproducible research methods.
I'm also looking forward to learning new things based on where my interests and my trainees' and collaborators' interests take me!

### How did I get here?

I followed a fairly traditional academic path---masters degree, PhD, postdoc---although with some breaks and other jobs in between (see my [CV](https://www.ericrscott.com/files/Eric%20Scott%20cv.pdf)).
During my PhD, I developed an interest and expertise in statistics and programming in R.
Even if it wasn't required for my research, I made excuses to learn new R packages and to stay up-to-date with the latest tools for reproducible data analysis.
I contributed to an [R package](https://docs.ropensci.org/webchem/) that I used in my research, and I developed an original [R package](https://github.com/Aariq/holodeck) or [two](https://github.com/Aariq/bumbl).
I also gained experience teaching statistics and R from TAing for Biostatistics and teaching Ecological Statistics and Data as an instructor of record in my last semester.

As a postdoc, I collaborated with my advisor remotely using GitHub on a number of projects and manuscripts.
As a side-project, I worked on a [collaborative manuscript](https://github.com/SORTEE-Github-Hackathon/manuscript) extolling the virtues of GitHub for collaborative research in ecology and evolutionary biology.

At some point in my job search (which was almost entirely for traditional faculty positions) I came across a job title I hadn't heard before: Research Software Engineer (RSE).
According to the [United States RSE Association](us-rse.org), an RSE is:

> We like an inclusive definition of Research Software Engineers to encompass those who regularly use expertise in programming to advance research.
> This includes researchers who spend a significant amount of time programming, full-time software engineers writing code to solve research problems, and those somewhere in-between.
> We aspire to apply the skills and practices of software development to research to create more robust, manageable, and sustainable research software.

I read that definition and thought, **"Hey! That's me! I do that!"**.
It turns out I had been an RSE as a PhD student and a postdoc and I was really excited to find a new community that I belonged in and a title that I liked a lot better than "data scientist".
I joined the [US-RSE Slack](https://us-rse.org/join/), which is where I think I first saw the job announcement (although it was definitely cross-posted in other Slacks I'm in).
