---
title: COVID-19 pushed me to try something new in my classroom, and I loved it!
# author: Eric Scott
date: '2020-05-27'
# slug: final-project
categories:
  - teaching
  - r
  - rmarkdown
code-tools: false
---

In March (which feels like years ago, now), when Universities started seriously thinking about their response to COVID-19, I was teaching Ecological Models and Data as instructor of record **and** finishing my dissertation up.
When teaching a class for the first time, things never go as planned, but switching entirely to online instruction for the last several weeks of class really took that to an extreme.
When students were asked to not come back after spring break, I had to make some decisions about how to continue the course.

Up to that point, I had assigned almost weekly homework assignments, but only given one exam so far.
There was one more exam and a cumulative final exam on the syllabus at that point.
I was also ahead of schedule in my lectures, so I was originally planning on doing exam 2, then adding some "special topics" lectures for the last couple of weeks before the final.
But after COVID-19, none of that made sense anymore.
I eventually decided to cancel exam 2 and forget about the extra lectures and just give the final and make exams a smaller percentage of the total grade.

I quickly realized I didn't know how to do an online final exam, and that there wasn't a previous year's final exam that I could base mine off of.
That's because in previous years this course (taught by Elizabeth Crone) had had a final **project**---something I'd never assigned in any class before.
I was skeptical that it would really replace a comprehensive final, but in the interest of being kind to my stressed students (and myself, who didn't want to write an exam from scratch), I assigned the final project.

The project involved analysis of data provided by the [Massachusetts Butterfly Club](https://www.naba.org/chapters/nabambc/).
Students would choose a butterfly species, and use the data for their species in a series of fairly well defined analyses to determine if their species was increasing or decreasing in abundance and if its phenology might be shifting.
So they would use the remaining weeks of class time to work on this analysis and ask questions.
But it didn't make sense to have everyone show up to a Zoom meeting and just work quietly every week.
My TA, Avalon Owens had the wonderful idea to split the students into 3 smaller working groups that we met with weekly.
When someone had a problem or issue that was pertinant to the whole class, I would make a video about it and post it for the class---just like saying "Listen up everyone, Joe had a question I think you'll all want to hear the answer to" in a *real* classroom.

The thing that surprised me most about this was how engaged the students were.
The final project was relatively structured questions and had detailed instructions like a long homework assignment, but by adding that tiny element of student choice (of butterfly species), I think it really transformed the attitude people took toward it.
Student choice also had the added benefit of demonstrating a **variety** of real world problems with data analysis that we wouldn't have seen if everyone was working on the same data---quite a few of which stumped me.
And, to a limited extent (limited because of quarantine) it did promote peer learning/teaching with a couple of students sharing code to deal with convergence errors that were common with very rare butterfly species.

Not every student used every statistical tool we learned in that course, but taking all the final projects together, I think it represented just about the entirety of the curriculum!
And students had a final report (produced in R Markdown) that was a real world data analysis project that they could use in a portfolio in future job interviews or graduate school applications.
All this is to say that I'm a convert.
Final projects can be an amazing assessment tool with so many benefits you wouldn't get from a traditional exam **and** the added benefit of less stress for your students.
Would this have worked as well in a class that was less about practical, applied skills?
Maybe not, but I'm encouraged enough by this semester to at least consider a final project in every class I teach from now on.
